"""Jar_Honey from the Pantry map (generated by sim/tools/roblox_to_innate.py).

Visual mesh is the full multi-primitive shape; the collider is its cylinder
body. Contact parameters are DEFAULTS and have not been tuned against the
gripper -- see 11_can.py for what tuned numbers look like.

drop_z is the height this object was AUTHORED at plus 1 cm, not the default
rest_z. Drop carries no z, so a prop meant to sit on a plinth would otherwise
be released below it and get shoved onto the floor; releasing from just above
its own support also avoids the bounce a long fall onto hard ground causes.
"""

from mars_sim_driver.props import Prop

PROP = Prop(
    name="pantry_jar_honey",
    label="?",
    title="Jar Honey",
    mesh="../objects/pantry_jar_honey.obj",
    collision="cylinder",
    size=(0.043, 0.054),
    rgba=(0.8078, 0.5804, 0.2118, 1.0),
    rest_z=0.054,
    drop_z=0.194,
)
