"""Jar_Stray from the Pantry map (generated by sim/tools/roblox_to_innate.py).

Visual mesh is the full multi-primitive shape; the collider is its cylinder
body. Contact parameters are DEFAULTS and have not been tuned against the
gripper -- see 11_can.py for what tuned numbers look like.

drop_z is the height this object was AUTHORED at plus 1 cm, not the default
rest_z. Drop carries no z, so a prop meant to sit on a plinth would otherwise
be released below it and get shoved onto the floor; releasing from just above
its own support also avoids the bounce a long fall onto hard ground causes.
"""

from mars_sim_driver.props import Prop

PROP = Prop(
    name="pantry_jar_stray",
    label="?",
    title="Jar Stray",
    mesh="../objects/pantry_jar_stray.obj",
    mesh_scale=0.5814,
    collision="cylinder",
    size=(0.0250, 0.0314),
    rgba=(0.698, 0.3059, 0.1882, 1.0),
    rest_z=0.0314,
    drop_z=0.194,
)
