# AUTO-GENERATED by the skill catalog from the physical skills on this robot.
# Regenerated on every skill change — do not edit; edits are overwritten.
"""Typed references to this robot's physical skills.

    from physical_skills import PickSocks

Use them anywhere a skill id goes: in an Agent's get_skills() list, or as a
declaration on a Skill (``pick: PickSocks``).
"""

from innate import TrainedSkill


class Untitled(TrainedSkill):
    """learned skill · 0 episodes · still in training"""

    skill_id = 'local/untitled'

class Wave(TrainedSkill):
    """replay skill · 0 episodes"""

    skill_id = 'local/wave'

class PickSocks(TrainedSkill):
    """learned skill · 0 episodes · still in training"""

    skill_id = 'innate-os/pick_socks'
# skipped innate-os/wave: class name Wave already taken by local/wave


def __getattr__(name):
    raise AttributeError(
        f"No physical skill named {name!r} on this robot (deleted, renamed, or not created yet?). "
        'Available: PickSocks, Untitled, Wave'
    )
