// Apartment sandbox's physics worker -- like urdfWorker.ts (see that file's
// header for the mjSpec/URDF-import technique), this loads the real
// mars.urdf into MuJoCo so the arm/head links' own geometry is actually
// simulated, not just the base. Differs from urdfWorker.ts in a few ways:
//   - No synthetic obstacles; ground plane sized to match the apartment
//     footprint (10x10, same as world.xml's stand-in floor).
//   - The apartment's real collision mesh -- the regenerated, per-room CoACD
//     decomposition from sim-mujoco/ (1283 hulls at a 0.05m concavity
//     threshold, floor stripped out in favor of the flat ground plane above;
//     see sim-mujoco/README.md's "Collision mesh regeneration" and
//     "Tightening the hulls further") -- is loaded here as static mesh geoms
//     hung off a single "apartment" body, added programmatically via the
//     mjSpec API (mjs_addMesh/mjs_addGeom) rather than a hand-authored MJCF
//     string, mirroring how the URDF's own joints/geoms are added below.
//     Superseded the old obj2mjcf/CoACD-default-threshold 112-hull set that
//     turned out to be the "robot spins crazily" bug (see world.xml's
//     now-stale TEMPORARY comment -- that sandbox still uses the old set
//     since nothing there reads apartment_collisions_v2/).
//   - Arm/head PD gains (and torque clamp) are live-tunable from the UI
//     (see set_gains) rather than fixed constants, since urdf-test's fixed
//     gains felt too soft. Note the URDF's own <dynamics damping="5"> per
//     joint means top speed under a saturated torque T is capped at T/5
//     rad/s regardless of gains -- e.g. the real effort=2.0 limit caps
//     speed at just 0.4 rad/s, which is why raising kp/kd alone can feel
//     like it does nothing once torque is already saturating.
//   - The base gets a planar joint (slide-x, slide-y, hinge-yaw stacked on
//     base_link) instead of urdfWorker.ts's free joint -- matching Genesis
//     (sim/src/simulation/simulation_node.py's base_x/base_y/base_yaw). A
//     free joint lets the arm's reaction torque tip or launch the base once
//     gains got aggressive enough to be responsive (confirmed headlessly:
//     fast joint-slider swings sent a free-jointed base's height shooting
//     over a meter into the air); a real MARS is a wheeled chassis that
//     physically can't do that, and the planar joint makes it impossible
//     here too.
//
// MESSAGE PROTOCOL
// main -> worker: {type:'init', spawn:{x,y,yaw}, collision?:'hulls'|'sdf'}
//                 {type:'reset', spawn:{x,y,yaw}}
//                 {type:'step', dt, vx, wz, joints:{[name]: targetRad}}
//                 {type:'set_gains', kp, kd, effortLimit}
//                 {type:'apply_force', anchorX, anchorY, anchorZ, fx, fy, fz}
//                 {type:'clear_force'}
// worker -> main: {type:'ready', joints:[{name,lower,upper}]}
//               | {type:'error', message}
//                 {type:'pose', x, y, z, yaw, joints:{[name]: rad}}

import loadMujoco from "@mujoco/mujoco";
import { ARM_HOME_POSITIONS } from "../robot/armHome";

const URDF_URL = "/robot/mars.urdf";

// See sim-mujoco/README.md's "Collision mesh regeneration" -- per-room CoACD
// decomposition, floor faces already stripped (the ground plane above stands
// in). manifest.json is a flat array of filenames since a browser can't list
// a directory; generated by decompose_rooms.py's output being copied in.
const COLLISION_BASE_URL = "/physics/apartment_collisions_v2/";

// Alternative collision source (init's collision:"sdf"): one watertight
// voxel-shell mesh per room (sim-mujoco/build_sdf_shells.py), loaded as
// native <geom type="sdf"> octree SDFs instead of convex hulls -- collision
// follows the true non-convex surface, no decomposition buffer or hull
// seams. Same flat manifest.json convention.
const SDF_BASE_URL = "/physics/apartment_sdf/";

export type CollisionMode = "hulls" | "sdf";

// Same +90deg-about-X quat world.xml and scene.ts's apartment.glb rotation
// use to convert the source mesh's Y-up authoring axis into this scene's
// Z-up (ROS/REP-103) convention.
const APARTMENT_QUAT = [0.7071068, 0.7071068, 0, 0] as const;

// See urdfWorker.ts for why joint6M (mimic of joint6) is handled separately
// rather than as a driven joint.
const DRIVEN_JOINTS = ["joint1", "joint2", "joint3", "joint4", "joint5", "joint6", "joint_head"] as const;
const MIMIC_JOINT = { name: "joint6M", source: "joint6", multiplier: -1 } as const;
const ALL_ARM_JOINTS = [...DRIVEN_JOINTS, MIMIC_JOINT.name];

// Base drive gains -- see worker.ts for the headless-tuning story. Verified
// headlessly against the real assembled URDF's mass (~1.4kg vs. the hand-
// written sandboxes' 3kg placeholder box) that these still settle to a
// stable cruise speed rather than diverging.
const KP_FORWARD = 200;
const KP_LATERAL = 40;
// KP_YAW used to be 6, which resonates with joint1's PD servo -- they act on
// the same (vertical/yaw) axis, and joint1's reaction torque on the base
// feeds directly into this velocity-hold controller. Confirmed headlessly:
// with the default arm gains, holding joint1 anywhere and then commanding a
// new target made it chatter violently (~26 rad/s sustained oscillation)
// with KP_YAW=6, and the instability threshold is a sharp cliff between 5.5
// (fine) and 6 (violent). 3 gives a wide, verified-stable margin (checked
// across all joints/targets, and even with arm kp raised to 150) while
// still holding yaw reasonably well when idle.
const KP_YAW = 3;

// Arm/head PD position-servo gains, live-tunable via set_gains (see the
// gain input boxes in main.ts) -- urdf-test's fixed KP=8/KD=0.6 felt too
// slow to track slider changes. Output torque is clamped to effortLimit,
// which defaults to mars.urdf's real <limit effort="2.0"> but is also
// tunable -- past that clamp, top speed is capped by the URDF's own
// per-joint damping=5 (effortLimit / 5 rad/s) regardless of kp/kd, so
// raising the clamp (not just the gains) is what actually buys speed.
// Defaults chosen empirically (see main.ts's gain inputs) rather than the
// URDF's real values: the real damping=5/effort=2.0 combo caps top speed at
// just 0.4 rad/s (torque saturates almost immediately, then damping alone
// limits speed), which felt unusably sluggish. 50/1/50 gives a reactive
// feel; still tunable live from the UI.
let kpJoint = 50;
let kdJoint = 1;
let effortLimit = 50; // N*m -- well past the real 2.0 limit, see above

let mujoco: Awaited<ReturnType<typeof loadMujoco>>;
let model: InstanceType<typeof mujoco.MjModel>;
let data: InstanceType<typeof mujoco.MjData>;
let baseBodyId = -1;

// qpos/dof addresses for the planar base's 3 joints -- see header comment.
let baseX: JointAdr = { qposAdr: -1, dofAdr: -1 };
let baseY: JointAdr = { qposAdr: -1, dofAdr: -1 };
let baseYaw: JointAdr = { qposAdr: -1, dofAdr: -1 };

let targetVx = 0;
let targetWz = 0;
let jointTargets: Record<string, number> = {};

let dragActive = false;
let dragAnchor = { x: 0, y: 0, z: 0 };
let dragForce = { x: 0, y: 0, z: 0 };

interface JointAdr {
  qposAdr: number;
  dofAdr: number;
}

interface JointHandle extends JointAdr {
  name: string;
}
let jointHandles: JointHandle[] = [];
let mimicHandle: JointHandle | null = null;

function readJointAdr(m: InstanceType<typeof mujoco.MjModel>, name: string): JointAdr {
  const jid = mujoco.mj_name2id(m, mujoco.mjtObj.mjOBJ_JOINT.value, name);
  return { qposAdr: m.jnt_qposadr[jid], dofAdr: m.jnt_dofadr[jid] };
}

/**
 * Fetches every collision hull OBJ, registers them in a fresh MjVFS, and
 * adds a static "apartment" body (one mesh geom per hull) to spec via the
 * mjSpec API -- same shape as world.xml's disabled apartment body, but
 * enabled (default contype/conaffinity) and pointed at the tighter
 * per-room hulls instead of the old flat 112-piece set. Returns the VFS,
 * which must be passed into mj_compile so it can resolve each mesh's file.
 *
 * margin/friction/solref/condim mirror sim-mujoco's build_world_xml
 * collision default class (see that file for why: 0.01 margin keeps the
 * perceived collision distance close to the visual surface; condim=6 +
 * this friction/solref combo is what settling on real furniture edges
 * needs to not be springy/jittery).
 */
async function loadApartmentCollisions(
  spec: ReturnType<typeof mujoco.parseXMLString>,
  def: NonNullable<ReturnType<typeof mujoco.mjs_getSpecDefault>>,
  mode: CollisionMode,
): Promise<InstanceType<typeof mujoco.MjVFS>> {
  const baseUrl = mode === "sdf" ? SDF_BASE_URL : COLLISION_BASE_URL;
  const geomType = mode === "sdf" ? mujoco.mjtGeom.mjGEOM_SDF : mujoco.mjtGeom.mjGEOM_MESH;
  const manifest: string[] = await (await fetch(`${baseUrl}manifest.json`)).json();

  const vfs = new mujoco.MjVFS();
  await Promise.all(
    manifest.map(async (filename) => {
      const buf = await (await fetch(`${baseUrl}${filename}`)).arrayBuffer();
      vfs.addBuffer(filename, new Uint8Array(buf));
    }),
  );

  const worldBody = mujoco.mjs_findBody(spec, "world")!;
  const apartmentBody = mujoco.mjs_addBody(worldBody, def)!;
  mujoco.mjs_setName(apartmentBody.element, "apartment");
  apartmentBody.quat[0] = APARTMENT_QUAT[0];
  apartmentBody.quat[1] = APARTMENT_QUAT[1];
  apartmentBody.quat[2] = APARTMENT_QUAT[2];
  apartmentBody.quat[3] = APARTMENT_QUAT[3];

  for (const filename of manifest) {
    const meshName = filename.replace(/\.obj$/, "");

    const mesh = mujoco.mjs_addMesh(spec, def)!;
    mujoco.mjs_setName(mesh.element, meshName);
    mesh.file = filename;

    const geom = mujoco.mjs_addGeom(apartmentBody, def)!;
    mujoco.mjs_setName(geom.element, `${meshName}_geom`);
    geom.type = geomType;
    geom.meshname = meshName;
    geom.condim = 6;
    // 7mm is the stress-tested floor: below it a hull seam corner-catches
    // (see sim-mujoco/README.md). Keep in sync with drive_apartment.py.
    geom.margin = 0.007;
    geom.friction[0] = 0.9;
    geom.friction[1] = 0.01;
    geom.friction[2] = 0.001;
    geom.solref[0] = 0.01;
    geom.solref[1] = 1;
    geom.rgba[3] = 0; // invisible -- apartment.glb is the real visual, this is collision-only
  }

  return vfs;
}

self.onerror = (event) => {
  self.postMessage({ type: "error", message: String(event) });
};

self.onmessage = async (e: MessageEvent) => {
  const msg = e.data;
  try {
    switch (msg.type) {
      case "init":
        await handleInit(msg.spawn, msg.collision ?? "hulls");
        break;
      case "reset":
        handleReset(msg.spawn);
        break;
      case "step":
        handleStep(msg.dt, msg.vx, msg.wz, msg.joints);
        break;
      case "set_gains":
        kpJoint = msg.kp;
        kdJoint = msg.kd;
        effortLimit = msg.effortLimit;
        break;
      case "apply_force":
        dragActive = true;
        dragAnchor = { x: msg.anchorX, y: msg.anchorY, z: msg.anchorZ };
        dragForce = { x: msg.fx, y: msg.fy, z: msg.fz };
        break;
      case "clear_force":
        dragActive = false;
        break;
    }
  } catch (err) {
    self.postMessage({ type: "error", message: String((err as Error)?.message ?? err) });
  }
};

async function handleInit(spawn: { x: number; y: number; yaw: number }, collision: CollisionMode): Promise<void> {
  mujoco = await loadMujoco();

  const urdfText = await (await fetch(URDF_URL)).text();
  const spec = mujoco.parseXMLString(urdfText);

  const baseBody = mujoco.mjs_findBody(spec, "base_link");
  if (!baseBody) {
    self.postMessage({ type: "error", message: "base_link not found in URDF" });
    return;
  }
  const def = mujoco.mjs_getSpecDefault(spec)!;

  // Planar base -- see header comment for why (not a free joint).
  const jointX = mujoco.mjs_addJoint(baseBody, def)!;
  mujoco.mjs_setName(jointX.element, "base_x");
  jointX.type = mujoco.mjtJoint.mjJNT_SLIDE;
  jointX.axis[0] = 1;
  jointX.axis[1] = 0;
  jointX.axis[2] = 0;

  const jointY = mujoco.mjs_addJoint(baseBody, def)!;
  mujoco.mjs_setName(jointY.element, "base_y");
  jointY.type = mujoco.mjtJoint.mjJNT_SLIDE;
  jointY.axis[0] = 0;
  jointY.axis[1] = 1;
  jointY.axis[2] = 0;

  const jointYaw = mujoco.mjs_addJoint(baseBody, def)!;
  mujoco.mjs_setName(jointYaw.element, "base_yaw");
  jointYaw.type = mujoco.mjtJoint.mjJNT_HINGE;
  jointYaw.axis[0] = 0;
  jointYaw.axis[1] = 0;
  jointYaw.axis[2] = 1;

  const worldBody = mujoco.mjs_findBody(spec, "world")!;

  const ground = mujoco.mjs_addGeom(worldBody, def)!;
  mujoco.mjs_setName(ground.element, "ground");
  ground.type = mujoco.mjtGeom.mjGEOM_PLANE;
  ground.size[0] = 10;
  ground.size[1] = 10;
  ground.size[2] = 0.1;
  ground.friction[0] = 0.9;
  ground.friction[1] = 0.01;
  ground.friction[2] = 0.001;
  ground.rgba[3] = 0; // invisible -- the apartment.glb mesh is the real visual floor

  // implicitfast damps out the single-step contact impulse spikes an
  // imperfect hull seam can produce, which is what let the 1283-hull
  // decomposition below be this tight without reintroducing the
  // "robot spins crazily" divergence -- see sim-mujoco/README.md's
  // "Tightening the hulls further" section for the full story.
  spec.option.integrator = mujoco.mjtIntegrator.mjINT_IMPLICITFAST.value;

  const vfs = await loadApartmentCollisions(spec, def, collision);

  model = mujoco.mj_compile(spec, vfs);
  vfs.delete();
  data = new mujoco.MjData(model);
  baseBodyId = mujoco.mj_name2id(model, mujoco.mjtObj.mjOBJ_BODY.value, "base_link");
  baseX = readJointAdr(model, "base_x");
  baseY = readJointAdr(model, "base_y");
  baseYaw = readJointAdr(model, "base_yaw");
  console.log(
    `[physics] loaded URDF: nbody=${model.nbody} njnt=${model.njnt} nq=${model.nq} ngeom=${model.ngeom} baseBodyId=${baseBodyId}`,
  );
  if (baseBodyId < 0) {
    self.postMessage({ type: "error", message: "base_link body not found in compiled model" });
    return;
  }

  const jointInfo: Array<{ name: string; lower: number; upper: number }> = [];
  jointHandles = [];
  for (const name of ALL_ARM_JOINTS) {
    const jid = mujoco.mj_name2id(model, mujoco.mjtObj.mjOBJ_JOINT.value, name);
    if (jid < 0) continue;
    const handle: JointHandle = { name, qposAdr: model.jnt_qposadr[jid], dofAdr: model.jnt_dofadr[jid] };
    if (name === MIMIC_JOINT.name) {
      mimicHandle = handle;
    } else {
      jointHandles.push(handle);
      jointInfo.push({ name, lower: model.jnt_range[jid * 2], upper: model.jnt_range[jid * 2 + 1] });
      jointTargets[name] = ARM_HOME_POSITIONS[name] ?? 0;
    }
  }

  setSpawn(spawn);
  setArmToTargets(); // start at the home pose, not the URDF's zero pose
  mujoco.mj_forward(model, data);
  self.postMessage({ type: "ready", joints: jointInfo });
}

/** Snaps qpos for every arm joint (+ the mimic) straight to jointTargets, skipping the PD ramp-up. */
function setArmToTargets(): void {
  for (const joint of jointHandles) data.qpos[joint.qposAdr] = jointTargets[joint.name];
  if (mimicHandle) data.qpos[mimicHandle.qposAdr] = MIMIC_JOINT.multiplier * (jointTargets[MIMIC_JOINT.source] ?? 0);
}

function handleReset(spawn: { x: number; y: number; yaw: number }): void {
  if (!model) return;
  mujoco.mj_resetData(model, data);
  for (const name of Object.keys(jointTargets)) jointTargets[name] = ARM_HOME_POSITIONS[name] ?? 0;
  setSpawn(spawn);
  setArmToTargets();
  mujoco.mj_forward(model, data);
  postPose();
}

function setSpawn(spawn: { x: number; y: number; yaw: number }): void {
  data.qpos[baseX.qposAdr] = spawn.x;
  data.qpos[baseY.qposAdr] = spawn.y;
  data.qpos[baseYaw.qposAdr] = spawn.yaw;
  const qvel = data.qvel;
  for (let i = 0; i < model.nv; i++) qvel[i] = 0;
}

let stepCount = 0;
let diverged = false;

function handleStep(dt: number, vx: number, wz: number, joints: Record<string, number> = {}): void {
  if (!model || diverged) return;
  targetVx = vx;
  targetWz = wz;
  for (const [name, value] of Object.entries(joints)) {
    if (name in jointTargets) jointTargets[name] = value;
  }

  const subStep = model.opt.timestep;
  const steps = Math.max(1, Math.round(dt / subStep));
  for (let i = 0; i < steps; i++) {
    applyBaseDrive();
    applyJointServo();
    mujoco.mj_step(model, data);
  }
  stepCount++;

  const qpos = data.qpos;
  if (!Number.isFinite(qpos[baseX.qposAdr]) || !Number.isFinite(qpos[baseYaw.qposAdr])) {
    diverged = true;
    self.postMessage({
      type: "error",
      message: `simulation diverged at step ${stepCount} (ncon=${data.ncon})`,
    });
    return;
  }

  postPose();
}

function applyBaseDrive(): void {
  const qvel = data.qvel;

  const yaw = data.qpos[baseYaw.qposAdr];
  const cos = Math.cos(yaw);
  const sin = Math.sin(yaw);
  const vxWorld = qvel[baseX.dofAdr];
  const vyWorld = qvel[baseY.dofAdr];

  const vForward = vxWorld * cos + vyWorld * sin;
  const vLateral = -vxWorld * sin + vyWorld * cos;
  const wzActual = qvel[baseYaw.dofAdr];

  const forceForward = KP_FORWARD * (targetVx - vForward);
  const forceLateral = -KP_LATERAL * vLateral;
  const torqueYaw = KP_YAW * (targetWz - wzActual);

  const xfrc = data.xfrc_applied;
  const base = baseBodyId * 6;
  xfrc[base + 0] = forceForward * cos - forceLateral * sin;
  xfrc[base + 1] = forceForward * sin + forceLateral * cos;
  xfrc[base + 2] = 0;
  xfrc[base + 3] = 0;
  xfrc[base + 4] = 0;
  xfrc[base + 5] = torqueYaw;

  if (dragActive) {
    const xipos = data.xipos;
    const rx = dragAnchor.x - xipos[baseBodyId * 3 + 0];
    const ry = dragAnchor.y - xipos[baseBodyId * 3 + 1];
    const rz = dragAnchor.z - xipos[baseBodyId * 3 + 2];
    xfrc[base + 0] += dragForce.x;
    xfrc[base + 1] += dragForce.y;
    xfrc[base + 2] += dragForce.z;
    xfrc[base + 3] += ry * dragForce.z - rz * dragForce.y;
    xfrc[base + 4] += rz * dragForce.x - rx * dragForce.z;
    xfrc[base + 5] += rx * dragForce.y - ry * dragForce.x;
  }
}

function servoTorque(target: number, q: number, v: number): number {
  const torque = kpJoint * (target - q) - kdJoint * v;
  return Math.max(-effortLimit, Math.min(effortLimit, torque));
}

function applyJointServo(): void {
  const qpos = data.qpos;
  const qvel = data.qvel;
  const qfrc = data.qfrc_applied;

  for (const joint of jointHandles) {
    const target = jointTargets[joint.name] ?? 0;
    qfrc[joint.dofAdr] = servoTorque(target, qpos[joint.qposAdr], qvel[joint.dofAdr]);
  }

  if (mimicHandle) {
    const target = MIMIC_JOINT.multiplier * (jointTargets[MIMIC_JOINT.source] ?? 0);
    qfrc[mimicHandle.dofAdr] = servoTorque(target, qpos[mimicHandle.qposAdr], qvel[mimicHandle.dofAdr]);
  }
}

function postPose(): void {
  const qpos = data.qpos;
  const joints: Record<string, number> = {};
  for (const joint of jointHandles) joints[joint.name] = qpos[joint.qposAdr];
  if (mimicHandle) joints[mimicHandle.name] = qpos[mimicHandle.qposAdr];

  self.postMessage({
    type: "pose",
    x: qpos[baseX.qposAdr],
    y: qpos[baseY.qposAdr],
    z: data.xipos[baseBodyId * 3 + 2],
    yaw: qpos[baseYaw.qposAdr],
    joints,
  });
}
