"""Photo from the Blaze map (generated by sim/tools/roblox_to_innate.py).

Visual mesh is the full multi-primitive shape; the collider is its box
body. Contact parameters are DEFAULTS and have not been tuned against the
gripper -- see 11_can.py for what tuned numbers look like.

drop_z is the height this object was AUTHORED at plus 1 cm, not the default
rest_z. Drop carries no z, so a prop meant to sit on a plinth would otherwise
be released below it and get shoved onto the floor; releasing from just above
its own support also avoids the bounce a long fall onto hard ground causes.
"""

from mars_sim_driver.props import Prop

PROP = Prop(
    name="blaze_photo",
    label="?",
    title="Photo",
    mesh="../objects/blaze_photo.obj",
    collision="box",
    size=(0.095, 0.006, 0.115),
    rgba=(0.4392, 0.3059, 0.1725, 1.0),
    rest_z=0.11947,
    drop_z=0.365,
)
