# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2026 Innate Inc
"""Generate the ``physical_skills`` package: one TrainedSkill subclass per
physical skill, so agents and skills reference them typed instead of by id
string. Rendering is pure (testable without ROS); the catalog calls
write_refs on every roster publish, and the content-compare inside makes
regeneration a no-op when nothing changed — which also keeps the workspace
hot-reload watcher from looping on our own writes."""

from __future__ import annotations

import os
import re
import textwrap
from pathlib import Path

_HEADER = '''\
# AUTO-GENERATED by the skill catalog from the physical skills on this robot.
# Regenerated on every skill change — do not edit; edits are overwritten.
"""Typed references to this robot's physical skills.

    from physical_skills import PickSocks

Use them anywhere a skill id goes: in an Agent's get_skills() list, or as a
declaration on a Skill (``pick: PickSocks``).
"""

from innate import TrainedSkill

'''


def class_name_for(skill_id: str) -> str:
    """``local/pick-socks`` -> ``PickSocks``. '' if no valid identifier results."""
    leaf = skill_id.rsplit("/", 1)[-1]
    parts = [p for p in re.split(r"[-_. ]+", leaf) if p]
    name = "".join(p[:1].upper() + p[1:] for p in parts)
    return name if name.isidentifier() else ""


def _docstring(entry: dict) -> str:
    """The ref's docstring: guidelines, then a summary line. Escaped so
    arbitrary guidelines text can't break out of the literal."""
    guidelines = (entry.get("guidelines") or "").strip()
    guidelines = guidelines.replace("\\", "\\\\").replace('"""', '\\"\\"\\"')
    kind = entry.get("type") or "physical"
    summary = f"{kind} skill · {entry.get('episode_count', 0)} episodes"
    if entry.get("in_training"):
        summary += " · still in training"
    if not guidelines:
        return f'    """{summary}"""'
    return textwrap.indent(f'"""{guidelines}\n\n{summary}\n"""', "    ")


def render_refs(entries: list[dict]) -> str:
    """The full ``physical_skills/__init__.py`` source for ``entries``
    (dicts with at least ``id``; optional guidelines/type/episode_count/
    in_training). Sorted for deterministic output; collisions and
    non-identifier names are skipped with a visible comment."""
    lines = [_HEADER]
    by_name: dict[str, str] = {}
    # local/ first: on a class-name collision the user's skill claims the
    # name, mirroring the catalog's plain-display-name precedence
    for entry in sorted(entries, key=lambda e: (not e["id"].startswith("local/"), e["id"])):
        skill_id = entry["id"]
        name = class_name_for(skill_id)
        if not name:
            lines.append(f"# skipped {skill_id}: cannot derive a Python class name\n")
            continue
        if name in by_name:
            lines.append(f"# skipped {skill_id}: class name {name} already taken by {by_name[name]}\n")
            continue
        by_name[name] = skill_id
        lines.append(f"\nclass {name}(TrainedSkill):\n{_docstring(entry)}\n\n    skill_id = {skill_id!r}\n")
    available = ", ".join(sorted(by_name)) or "none — no physical skills on this robot yet"
    lines.append(
        "\n\ndef __getattr__(name):\n"
        "    raise AttributeError(\n"
        '        f"No physical skill named {name!r} on this robot (deleted, renamed, '
        'or not created yet?). "\n'
        f"        {'Available: ' + available!r}\n"
        "    )\n"
    )
    return "".join(lines)


def write_refs(package_dir: str | Path, content: str, logger) -> None:
    """Write ``physical_skills/__init__.py`` atomically, skipping identical
    content. Failure is logged, never raised — refs are a convenience and
    must not break skill loading."""
    try:
        package_dir = Path(package_dir)
        target = package_dir / "__init__.py"
        try:
            if target.read_text() == content:
                return
        except OSError:
            pass
        package_dir.mkdir(parents=True, exist_ok=True)
        tmp = target.with_name("__init__.py.tmp")
        tmp.write_text(content)
        os.replace(tmp, target)
        logger.info(f"Regenerated physical skill refs at {target}")
    except OSError as e:
        logger.warning(f"Could not write physical skill refs: {e}")
