# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2026 Innate Inc
"""Generate the ``physical_skills`` package: one TrainedSkill subclass per
physical skill, so agents and skills reference them typed instead of by id
string. Each recording folder also gets a generated ``__init__.py`` shim
next to its metadata.json (see render_dir_shims), so the pack-local spelling
``from innate_skills.pick_socks import PickSocks`` resolves to the same
class — the folder becomes an importable package while staying a data dir
to the scanner (workspace_import skips metadata dirs from proactive import;
the shim loads transitively). Rendering is pure (testable without ROS); the
catalog calls the writers on every roster publish, and the content-compare
inside makes regeneration a no-op when nothing changed — which also keeps
the workspace hot-reload watcher from looping on our own writes."""

from __future__ import annotations

import os
import re
import textwrap
from pathlib import Path

from .physical import has_physical_metadata

_HEADER = '''\
# AUTO-GENERATED by the skill catalog from the physical skills on this robot.
# Regenerated on every skill change — do not edit; edits are overwritten.
"""Typed references to this robot's physical skills.

Import a ref from its recording folder; this package is the generated
definition site the folder shims re-export from:

    from innate_skills.pick_socks import PickSocks  # the usual spelling
    from physical_skills import PickSocks           # same class

Use them anywhere a skill id goes: in an Agent's get_skills() list, or as a
declaration on a Skill (``pick: PickSocks``).
"""

from innate import TrainedSkill

'''

# First line of every dir shim — write_dir_shims only ever overwrites or
# removes files that start with it, so a hand-written __init__.py is safe.
_SHIM_MARKER = "# AUTO-GENERATED physical-skill ref"

# Dir shims are runtime-owned and gitignored (workspace/innate_skills/
# .gitignore): committing one gives the path two writers, and a robot whose
# running code is ahead of its checkout then aborts `git pull`/`innate update`
# on the untracked collision. {imported} is just "{name}", or
# "{qualified} as {name}" when another skill took the plain name.

_DIR_SHIM = (
    _SHIM_MARKER
    + ''' by the skill catalog — do not edit; edits are overwritten.
"""Typed ref to {skill_id!r}, the recording in this folder.

Same class either way:

    from physical_skills import {imported}
"""

from physical_skills import {imported}

__all__ = ["{name}"]
'''
)


def class_name_for(skill_id: str) -> str:
    """``local/pick-socks`` -> ``PickSocks``. '' if no valid identifier results."""
    leaf = skill_id.rsplit("/", 1)[-1]
    parts = [p for p in re.split(r"[-_. ]+", leaf) if p]
    name = "".join(p[:1].upper() + p[1:] for p in parts)
    return name if name.isidentifier() else ""


def _docstring(entry: dict) -> str:
    """The ref's docstring: guidelines, then a summary line. Escaped so
    arbitrary guidelines text can't break out of the literal."""
    guidelines = (entry.get("guidelines") or "").strip()
    guidelines = guidelines.replace("\\", "\\\\").replace('"""', '\\"\\"\\"')
    kind = entry.get("type") or "physical"
    summary = f"{kind} skill · {entry.get('episode_count', 0)} episodes"
    if entry.get("in_training"):
        summary += " · still in training"
    if not guidelines:
        return f'    """{summary}"""'
    return textwrap.indent(f'"""{guidelines}\n\n{summary}\n"""', "    ")


def _claim_order(entry: dict) -> tuple[bool, str]:
    """local/ first, then by id — the catalog's plain-display-name precedence."""
    return (not entry["id"].startswith("local/"), entry["id"])


def _claimed(entries: list[dict]) -> dict[str, dict]:
    """``{class_name: entry}`` in deterministic claim order.

    local/ first: on a collision the user's skill claims the plain name and
    the loser is re-claimed qualified (``Wave`` taken -> ``WaveInnateOs``),
    mirroring the catalog publishing its display name as 'wave (innate-os)' —
    a live skill must not lose its ref to a flat-namespace clash. Plain names
    are all claimed before any fallback, so a fallback can't displace one.

    The qualified name can collide in turn — a leaf that spells out another
    skill's leaf+pack (``local/wave-innate-os`` vs ``innate-os/wave``), or two
    packs normalizing alike (``innate-os`` / ``innate_os``) — so it counts up
    (``WaveInnateOs2``) until something is free. Every entry with a derivable
    identifier ends up claimed; nothing is dropped for a name clash. Numbered
    names are the pathological tail, and unlike the plain and qualified names
    they depend on the rest of the roster: adding a skill can renumber one,
    rewriting its shim. Shared by render_refs and render_dir_shims
    so they can't disagree."""
    claims: dict[str, dict] = {}
    losers: list[tuple[str, dict]] = []
    for entry in sorted(entries, key=_claim_order):
        name = class_name_for(entry["id"])
        if not name:
            continue
        if name in claims:
            losers.append((name, entry))
        else:
            claims[name] = entry
    for name, entry in losers:
        # no suffix (an id with no pack prefix) leaves base == the taken plain
        # name, so the counter alone separates it
        base = name + class_name_for(entry["id"].rpartition("/")[0])
        candidate, n = base, 2
        while candidate in claims:
            candidate, n = f"{base}{n}", n + 1
        claims[candidate] = entry
    return claims


def render_refs(entries: list[dict]) -> dict[str, str]:
    """The full ``physical_skills`` package for ``entries`` (dicts with at
    least ``id``; optional guidelines/type/episode_count/in_training), as
    ``{filename: source}`` — write_refs prunes anything else, so a file
    dropped from this mapping is deleted on the next publish. Sorted for
    deterministic output. A name collision qualifies the loser rather than
    dropping it (see _claimed); only entries left with no usable name at
    all are skipped, with a visible comment."""
    lines = [_HEADER]
    names_by_id = {entry["id"]: name for name, entry in _claimed(entries).items()}
    by_name: dict[str, str] = {}
    for entry in sorted(entries, key=_claim_order):
        skill_id = entry["id"]
        name = names_by_id.get(skill_id)
        if not name:
            lines.append(f"# skipped {skill_id}: no usable Python class name\n")
            continue
        by_name[name] = skill_id
        lines.append(f"\nclass {name}(TrainedSkill):\n{_docstring(entry)}\n\n    skill_id = {skill_id!r}\n")
    available = ", ".join(sorted(by_name)) or "none — no physical skills on this robot yet"
    lines.append(
        "\n\ndef __getattr__(name):\n"
        "    raise AttributeError(\n"
        '        f"No physical skill named {name!r} on this robot (deleted, renamed, '
        'or not created yet?). "\n'
        f"        {'Available: ' + available!r}\n"
        "    )\n"
    )
    return {"__init__.py": "".join(lines)}


def write_refs(package_dir: str | Path, files: dict[str, str], logger) -> None:
    """Write the ``physical_skills`` package atomically: each file in
    ``files`` (skipping identical content), then remove generated modules
    whose skill is gone. Failure is logged, never raised — refs are a
    convenience and must not break skill loading."""
    try:
        package_dir = Path(package_dir)
        package_dir.mkdir(parents=True, exist_ok=True)
        changed = 0
        for filename, content in files.items():
            target = package_dir / filename
            try:
                if target.read_text() == content:
                    continue
            except OSError:
                pass
            # pid in the tmp name: the skills server and brain_client both
            # write these files, and a shared tmp path would let them interleave
            tmp = target.with_name(f"{filename}.{os.getpid()}.tmp")
            tmp.write_text(content)
            os.replace(tmp, target)
            changed += 1
        # the whole directory is generated (and gitignored), so any .py we
        # didn't just render is a stale ref for a deleted or renamed skill
        for stale in package_dir.glob("*.py"):
            if stale.name not in files:
                stale.unlink(missing_ok=True)
                changed += 1
        if changed:
            logger.info(f"Regenerated physical skill refs at {package_dir} ({changed} files)")
    except OSError as e:
        logger.warning(f"Could not write physical skill refs: {e}")


def render_dir_shims(entries: list[dict]) -> dict[str, str | None]:
    """``{<skill_dir>/__init__.py: source}`` for entries that carry a ``dir``.

    The shim makes the recording folder an importable package, so the
    pack-local spelling (``from innate_skills.wave import Wave``) resolves to
    the class defined in ``physical_skills`` — under an alias when that class
    is qualified, so a collision rewrites the shim in place instead of
    deleting it (and reverts it verbatim once the collision goes). ``None``
    marks a shim to *remove*: the entry got no class name at all, so a
    previously written shim must not linger and re-export a name that now
    belongs to another skill."""
    claims = _claimed(entries)
    shims: dict[str, str | None] = {}
    for claimed_name, entry in claims.items():
        if entry.get("dir"):
            # the folder keeps exporting its plain name — only the import
            # line changes when this skill lost the plain name to another
            name = class_name_for(entry["id"])
            imported = name if claimed_name == name else f"{claimed_name} as {name}"
            path = os.path.join(entry["dir"], "__init__.py")
            shims[path] = _DIR_SHIM.format(skill_id=entry["id"], name=name, imported=imported)
    winner_ids = {entry["id"] for entry in claims.values()}
    for entry in entries:
        if entry.get("dir") and entry["id"] not in winner_ids:
            shims.setdefault(os.path.join(entry["dir"], "__init__.py"), None)
    return shims


def write_dir_shims(shims: dict[str, str | None], logger) -> None:
    """Write (or remove, for ``None``) ref shims inside recording folders.

    Only files whose first line is the shim marker are ever overwritten or
    deleted — a hand-written ``__init__.py`` in a skill folder is left alone
    with a warning. Content-compared like write_refs so an unchanged roster
    writes nothing. Failure is logged, never raised."""
    for path_str, content in shims.items():
        try:
            path = Path(path_str)
            try:
                existing = path.read_text()
            except OSError:
                existing = None
            if content is None:
                if existing is not None and existing.startswith(_SHIM_MARKER):
                    path.unlink(missing_ok=True)
                    logger.info(f"Removed stale physical skill ref {path}")
                continue
            if existing == content:
                continue
            if existing is not None and not existing.startswith(_SHIM_MARKER):
                logger.warning(f"Not writing physical skill ref over hand-written {path}")
                continue
            if not path.parent.is_dir():
                continue  # skill dir vanished between roster build and now
            tmp = path.with_name(f"__init__.py.{os.getpid()}.tmp")
            tmp.write_text(content)
            os.replace(tmp, path)
            logger.info(f"Wrote physical skill ref {path}")
        except OSError as e:
            logger.warning(f"Could not write physical skill ref {path_str}: {e}")


def prune_dir_shims(package_dirs: list[str], live_shims: dict[str, str | None], logger) -> None:
    """Remove generated ref shims left behind in folders that stopped being
    recording folders (metadata.json deleted or emptied while the generated
    ``__init__.py`` stayed) — render_dir_shims can't list those, since it
    only sees rostered entries. A folder that still holds real metadata
    keeps its shim even when its skill is off the roster this publish
    (corrupt trajectory, unreadable metadata): deleting one over a
    transient/fixable fault would break
    ``from innate_skills.<x> import <X>`` everywhere. Scans one
    level under each skill package root, the only place recording folders
    live; only marker-bearing files are ever deleted, so hand-written
    subpackage ``__init__.py`` files are untouched. Failure is logged, never
    raised."""
    keep = {os.path.realpath(p) for p, content in live_shims.items() if content is not None}
    for root in package_dirs:
        try:
            for init in Path(root).glob("*/__init__.py"):
                if os.path.realpath(init) in keep:
                    continue
                if has_physical_metadata(init.parent):
                    continue  # still a recording folder — off-roster isn't orphaned
                try:
                    if init.read_text().startswith(_SHIM_MARKER):
                        init.unlink(missing_ok=True)
                        logger.info(f"Removed orphaned physical skill ref {init}")
                except OSError:
                    continue
        except OSError as e:
            logger.warning(f"Could not prune physical skill refs under {root}: {e}")
