# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2026 Innate Inc
import json
import math
import threading
import time
from dataclasses import dataclass
from typing import Literal, cast

import numpy as np
from innate_skills.person_tracking import TRACK_PERIOD, FaceBox, _PersonTrackingSkill
from innate_skills.turn_in_place import TurnInPlace
from std_msgs.msg import String

from innate import Lidar, Odometry, SkillReturn, resource

Action = Literal["find", "approach"]
Direction = Literal["front", "left", "right", "behind"]
AudioSide = Literal["unknown", "left", "right", "center"]

DIRECTION_ANGLE: dict[Direction, float] = {
    "front": 0.0,
    "left": 90.0,
    "right": -90.0,
    "behind": 180.0,
}

CALLER_AUDIO_TOPIC = "/mic/caller_audio"
LOCK_MAX_AGE_SECONDS = 300.0
SCAN_SPEED = 0.3
SCAN_TIMEOUT = 25.0
MAX_LINEAR_SPEED = 0.12
MAX_ANGULAR_SPEED = 0.45
APPROACH_TIMEOUT = 30.0
MAX_APPROACH_DISTANCE = 2.0
LIDAR_STOP_DISTANCE = 0.35
LOST_FACE_FRAMES = 6
LEFT_BOX_FRAMES = 2
CMD_DURATION = 0.4


@dataclass(frozen=True)
class AudioSnapshot:
    side: str = "unknown"
    level: float = 0.0
    confidence: float = 0.0
    timestamp: float = 0.0
    directional: bool = False


class AudioBearingReader:
    def __init__(self, node):
        self._snapshot = AudioSnapshot()
        self._lock = threading.Lock()
        self._sub = node.create_subscription(String, CALLER_AUDIO_TOPIC, self._on_audio, 10)

    def _on_audio(self, msg: String) -> None:
        try:
            payload = json.loads(msg.data)
            snapshot = AudioSnapshot(
                side=str(payload.get("side", "unknown")),
                level=float(payload.get("level", 0.0)),
                confidence=float(payload.get("confidence", 0.0)),
                timestamp=float(payload.get("timestamp", 0.0)),
                directional=bool(payload.get("directional", False)),
            )
        except (json.JSONDecodeError, TypeError, ValueError):
            return
        with self._lock:
            self._snapshot = snapshot

    def latest(self, max_age: float = 3.0) -> AudioSnapshot:
        with self._lock:
            snapshot = self._snapshot
        if snapshot.timestamp <= 0.0 or time.time() - snapshot.timestamp > max_age:
            return AudioSnapshot()
        return snapshot


class CallerInteraction(_PersonTrackingSkill):
    """Find, remember, and safely approach the person who called Mars."""

    lidar: Lidar | None
    odom: Odometry
    turn_in_place: TurnInPlace

    @resource
    def _audio_reader(self) -> AudioBearingReader:
        return AudioBearingReader(self.node)

    def guidelines(self) -> str:
        return (
            "Handle a caller-location command generated by the microphone. action='find' turns "
            "toward direction, scans for a face, centers it, and remembers the lock. "
            "action='approach' drives toward a locked face until it leaves the centering box."
        )

    def execute(
        self,
        action: Action,
        direction: Direction = "front",
        audio_side: AudioSide = "unknown",
        audio_confidence: float = 0.0,
    ) -> SkillReturn:
        action = cast(Action, action.strip().lower())
        direction = cast(Direction, direction.strip().lower())
        audio_side = cast(AudioSide, audio_side.strip().lower())
        if action not in ("find", "approach"):
            self.fail("action must be 'find' or 'approach'")
        if direction not in DIRECTION_ANGLE:
            self.fail("direction must be front, left, right, or behind")
        if audio_side not in ("unknown", "left", "right", "center"):
            audio_side = "unknown"

        if action == "find":
            return self._find(direction, self._trusted_side(audio_side, audio_confidence))
        return self._approach(direction, self._trusted_side(audio_side, audio_confidence))

    def _find(self, direction: Direction, audio_side: str) -> SkillReturn:
        angle = DIRECTION_ANGLE[direction]
        if angle:
            self.turn_in_place(angle_degrees=angle, speed=0.4)

        locked = self._center_face(audio_side, timeout=10.0, look_up=True)
        if locked is None and self._scan_until_face(audio_side):
            locked = self._center_face(self._live_side(audio_side), timeout=10.0, look_up=True)
        if locked is None:
            self.say("I could not find you. Please call my name again.")
            self.fail("No face found in the caller's direction")

        tilt, face = locked
        odom = self.odom
        self.storage["caller_lock"] = {
            "x": odom.x,
            "y": odom.y,
            "theta": odom.theta,
            "tilt": tilt,
            "face_width": face.width,
            "audio_level": self._audio_reader.latest().level,
            "timestamp": time.time(),
        }
        self.say("I found you.")
        return f"Centered on the caller from the {direction}"

    def _scan_until_face(self, audio_side: str) -> bool:
        started = time.monotonic()
        last_yaw = self.odom.theta
        turned = 0.0
        sign = -1.0 if audio_side == "right" else 1.0
        try:
            while turned < 360.0 and time.monotonic() - started < SCAN_TIMEOUT:
                side = self._live_side(audio_side)
                if self._select_face(self._visible_faces(), side) is not None:
                    return True
                self.mobility.send_cmd_vel(angular_z=sign * SCAN_SPEED, duration=CMD_DURATION)
                self.sleep(TRACK_PERIOD)
                yaw = self.odom.theta
                turned += abs(math.degrees(math.atan2(math.sin(yaw - last_yaw), math.cos(yaw - last_yaw))))
                last_yaw = yaw
        finally:
            self.mobility.stop()
        return False

    def _approach(self, direction: Direction, audio_side: str) -> SkillReturn:
        side = self._live_side(audio_side)
        face = self._select_face(self._visible_faces(), side)
        if face is None or not self._in_tolerance(face):
            lock = self.storage.get("caller_lock")
            if isinstance(lock, dict) and time.time() - float(lock.get("timestamp", 0.0)) <= LOCK_MAX_AGE_SECONDS:
                target_theta = float(lock["theta"])
                turn = math.degrees(
                    math.atan2(math.sin(target_theta - self.odom.theta), math.cos(target_theta - self.odom.theta))
                )
                if abs(turn) > 8.0:
                    self.turn_in_place(angle_degrees=turn, speed=0.4)
        locked = self._center_face(side, timeout=10.0, look_up=True)
        if locked is None and self._scan_until_face(audio_side):
            locked = self._center_face(self._live_side(audio_side), timeout=10.0, look_up=True)
        if locked is None:
            self.say("Which direction are you?")
            self.fail("No locked face to approach")
        return self._servo_to_caller(direction, audio_side)

    def _servo_to_caller(self, direction: Direction, audio_side: str) -> SkillReturn:
        started = time.monotonic()
        start_position = self.odom.position
        lost_frames = 0
        left_box_frames = 0
        was_inside = False
        tracked: FaceBox | None = None
        try:
            while time.monotonic() - started < APPROACH_TIMEOUT:
                self._check_safety(start_position)
                faces = self._visible_faces()
                face = self._tracked_face(faces, tracked, self._live_side(audio_side))
                if face is None:
                    tracked = None
                    lost_frames += 1
                    self.mobility.stop()
                    if lost_frames > LOST_FACE_FRAMES:
                        self.fail("Lost the caller's face while approaching")
                    self.sleep(TRACK_PERIOD)
                    continue

                tracked = face
                lost_frames = 0
                x_error = face.center_x - 0.5
                if self._in_tolerance(face):
                    was_inside = True
                    left_box_frames = 0
                    angular = float(np.clip(-1.5 * x_error, -MAX_ANGULAR_SPEED, MAX_ANGULAR_SPEED))
                    self.mobility.send_cmd_vel(linear_x=MAX_LINEAR_SPEED, angular_z=angular, duration=CMD_DURATION)
                    self.sleep(TRACK_PERIOD)
                    continue

                if was_inside:
                    left_box_frames += 1
                    self.mobility.stop()
                    if left_box_frames >= LEFT_BOX_FRAMES:
                        self.say("There. I got closer. Now what?")
                        return f"Reached the caller from the {direction}"
                    self.sleep(TRACK_PERIOD)
                    continue

                angular = float(np.clip(-1.5 * x_error, -MAX_ANGULAR_SPEED, MAX_ANGULAR_SPEED))
                self.mobility.send_cmd_vel(linear_x=0.0, angular_z=angular, duration=CMD_DURATION)
                self.sleep(TRACK_PERIOD)
        finally:
            self.mobility.stop()
        self.fail("Timed out while approaching the caller")

    def _check_safety(self, start_position: tuple[float, float]) -> None:
        if math.dist(start_position, self.odom.position) > MAX_APPROACH_DISTANCE:
            self.fail("Stopped after reaching the maximum approach distance")
        scan = self.lidar
        if scan is None:
            self.fail("Cannot approach safely without lidar")
        obstacle = scan.min_range(-30.0, 30.0)
        if obstacle is not None and obstacle < LIDAR_STOP_DISTANCE:
            self.fail(f"Stopped for an obstacle {obstacle:.2f} meters ahead")

    def _trusted_side(self, side: AudioSide, confidence: float) -> str:
        return side if confidence >= 0.5 else self._live_side("unknown")

    def _live_side(self, fallback: str) -> str:
        snapshot = self._audio_reader.latest()
        if snapshot.directional and snapshot.confidence >= 0.5:
            return snapshot.side
        return fallback
