"""Ball_Hall from the Household map (generated by sim/tools/roblox_to_innate.py).

Visual mesh is the full multi-primitive shape; the collider is its sphere
body. Contact parameters are DEFAULTS and have not been tuned against the
gripper -- see 11_can.py for what tuned numbers look like.

drop_z is the height this object was AUTHORED at plus 1 cm, not the default
rest_z. Drop carries no z, so a prop meant to sit on a plinth would otherwise
be released below it and get shoved onto the floor; releasing from just above
its own support also avoids the bounce a long fall onto hard ground causes.
"""

from mars_sim_driver.props import Prop

PROP = Prop(
    name="household_ball_hall",
    label="🏐",
    title="Ball Hall",
    mesh="../objects/household_ball_hall.obj",
    collision="sphere",
    size=(0.07,),
    rgba=(0.902, 0.7294, 0.2431, 1.0),
    rest_z=0.07,
    drop_z=0.08,
)
