"""Book_Bed from the Household map (generated by sim/tools/roblox_to_innate.py).

Visual mesh is the full multi-primitive shape; the collider is its box
body. Contact parameters are DEFAULTS and have not been tuned against the
gripper -- see 11_can.py for what tuned numbers look like.

drop_z is the height this object was AUTHORED at plus 1 cm, not the default
rest_z. Drop carries no z, so a prop meant to sit on a plinth would otherwise
be released below it and get shoved onto the floor; releasing from just above
its own support also avoids the bounce a long fall onto hard ground causes.
"""

from mars_sim_driver.props import Prop

PROP = Prop(
    name="household_book_bed",
    label="📕",
    title="Book Bed",
    mesh="../objects/household_book_bed.obj",
    collision="box",
    size=(0.071, 0.0515, 0.0085),
    rgba=(0.9333, 0.902, 0.8157, 1.0),
    rest_z=0.017,
    drop_z=0.497,
)
