"""Mug_Kitchen from the Household map (generated by sim/tools/roblox_to_innate.py).

Visual mesh is the full multi-primitive shape; the collider is its cylinder
body. Contact parameters are DEFAULTS and have not been tuned against the
gripper -- see 11_can.py for what tuned numbers look like.

drop_z is the height this object was AUTHORED at plus 1 cm, not the default
rest_z. Drop carries no z, so a prop meant to sit on a plinth would otherwise
be released below it and get shoved onto the floor; releasing from just above
its own support also avoids the bounce a long fall onto hard ground causes.
"""

from mars_sim_driver.props import Prop

PROP = Prop(
    name="household_mug_kitchen",
    label="☕",
    title="Mug Kitchen",
    mesh="../objects/household_mug_kitchen.obj",
    mesh_scale=0.5882,
    collision="cylinder",
    size=(0.0250, 0.0279),
    # Blue, not near-white (0.969, 0.965, 0.953): a WHITE mug on the white
    # kitchen floor of an apartment whose walls, floors and half the furniture
    # are the same near-white was unresolvable at the robot's 640x480 -- a
    # probe agent that had just aced two other maps could not find the room,
    # let alone the mug, and the live robot scored 0/2. Blue rather than red
    # because household_mug_living is already red and the two must never be
    # confusable in a fetch. Brief updated to match. Post-dates the Aug 16
    # live run.
    rgba=(0.17, 0.42, 0.78, 1.0),
    rest_z=0.0279,
    drop_z=0.9375,
)
